-- =============================================================================
-- DEPRECATED: Single source of truth for D1 schema is /migrations/
-- Do NOT execute this file directly.
-- Apply migrations using Cloudflare Wrangler:
--   wrangler d1 migrations apply velnar-db --local
--   wrangler d1 migrations apply velnar-db --remote
--
-- Canonical Migrations:
--   - migrations/0001_initial_schema.sql
--   - migrations/0002_indexes_and_performance.sql
--   - migrations/0003_ai_intelligence_layer.sql
--   - migrations/0004_growth_action_policy_hardening.sql
-- =============================================================================
